/*
 * Black API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blackapi

import (
	"encoding/json"
)

// NotFoundError struct for NotFoundError
type NotFoundError struct {
	Status string `json:"status"`
	Code string `json:"code"`
	AdditionalProperties map[string]interface{}
}

type _NotFoundError NotFoundError

// NewNotFoundError instantiates a new NotFoundError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotFoundError(status string, code string, ) *NotFoundError {
	this := NotFoundError{}
	this.Status = status
	this.Code = code
	return &this
}

// NewNotFoundErrorWithDefaults instantiates a new NotFoundError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotFoundErrorWithDefaults() *NotFoundError {
	this := NotFoundError{}
	return &this
}

// GetStatus returns the Status field value
func (o *NotFoundError) GetStatus() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *NotFoundError) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *NotFoundError) SetStatus(v string) {
	o.Status = v
}

// GetCode returns the Code field value
func (o *NotFoundError) GetCode() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *NotFoundError) GetCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *NotFoundError) SetCode(v string) {
	o.Code = v
}

func (o NotFoundError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["code"] = o.Code
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *NotFoundError) UnmarshalJSON(bytes []byte) (err error) {
	varNotFoundError := _NotFoundError{}

	if err = json.Unmarshal(bytes, &varNotFoundError); err == nil {
		*o = NotFoundError(varNotFoundError)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "code")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNotFoundError struct {
	value *NotFoundError
	isSet bool
}

func (v NullableNotFoundError) Get() *NotFoundError {
	return v.value
}

func (v *NullableNotFoundError) Set(val *NotFoundError) {
	v.value = val
	v.isSet = true
}

func (v NullableNotFoundError) IsSet() bool {
	return v.isSet
}

func (v *NullableNotFoundError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotFoundError(val *NotFoundError) *NullableNotFoundError {
	return &NullableNotFoundError{value: val, isSet: true}
}

func (v NullableNotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotFoundError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


